#!/bin/sh
#
# $Id$
#
# A simple apache log file rotate script - note that we
# can not rotate any more often than once a day.  The script
# specifically prevents this as the file names generated are
# only unique per day.

## NOTE!  This needs to be where the logs are
cd /home/equine/private/subversion/apache/logs	|| exit

OLD=`date '+%Y-%m-%d'`
FLAG=${OLD}.flag

# Get an array of the existing files in date order
filelist=( `ls -t *_log.gz 2>/dev/null` )

# Delete all old files over n-ago (see value below)
# This means that, for example, 60 would be 30 days
# ago since each day has 2 files.
index=60
while [ "$index" -lt "${#filelist[@]}" ]
do
	echo ${filelist[$index]}
	let "index = $index + 1"
done

# Check if we have already run today
if [ ! -f $FLAG.gz ]; then
	# Delete any old flags
	rm -f *.flag.gz junk

	# Flag that we are running / have run today
	echo >$FLAG

	# Compress any older logs that have not
	# been compressed yet and the flag (not that it helps)
	gzip -9 *.access_log *.error_log $FLAG

	# Now, move the current logs into the current date
	# "old" file.
	mv access_log ${OLD}.access_log
	mv error_log ${OLD}.error_log

	# Tell apache to gracefully restart itself.  This
	# causes it to reload its configuration and to reopen
	# the log files (which will then be new)
	../bin/apachectl graceful
fi
